#!/bin/sh

################################################################################
#
#	expjoball
#
#	A tool to export all dbms_jobs from Oracle Database 
#
#	This tool has been tested in SQL*Plus 10 or above to give immediately
#       loadable dbms_jobs
#
#
#   Version	Date		Modified by	Descriptions
#  --------------------------------------------------------------------------
#   1.0.0	20090807	Kane Lai	First release
#   1.0.1	20120402	Kane Lai	Major fixes
#
################################################################################


version="1.0.1"

if [ $# -lt 1 ]; then
	echo "expjoball v$version - A tool to export all dbms_jobs from Oracle Database"
	echo "Exported dbms_jobs will be named load_job.sql in the current directory"
	echo "Usage:\t`basename $0` [db_conn_str]"
	echo "    \"db_conn_str\": Oracle Database connection string to be passed to sqlplus, e.g. admin/mypassword@ora10g"
	exit 1
fi

db_conn_str=$1
is_conn_str_ok=`echo $db_conn_str | grep -ic /`
if [ $is_conn_str_ok -ne 1 ]; then
	echo "Oracle Database connection string must be of the format \"username/password[@connect_identifier]\""
	exit 1
fi

load_job_script="load_job.sql"

# prepare script to load dbms_jobs automatically
if [ -f $load_job_script ]; then
	rm $load_job_script
fi
touch $load_job_script

# execute SQL script
sqlplus -SL $db_conn_str << EOSQL >> /dev/null
set echo off
set maxdata 50000
set long 50000
set longchunksize 1000
set pages 0 lines 32767
set heading off
set verify off
set termout off
set feedback off
set trims on
set timing off
spool $load_job_script
prompt var jobno number
prompt
select	'exec dbms_job.submit('||
	'job=>:jobno,'||
	'what=>'''||replace(what,'''', '''''')||''','||
	'next_date=>sysdate,'||
	'interval=>'''||interval||''');'||
	chr(10)||
	'print jobno'
from	user_jobs
order by job;
spool off
exit
EOSQL

# export successful
echo "DBMS_JOBS exported successfully"
 
