#!/bin/sh

################################################################################
#
#	expschema
#
#	A tool to export schema from Oracle Database 
#
#	This tool has been tested in SQL*Plus 10 or above to give immediately
#       loadable SQL scripts
#
#
#   Version	Date		Modified by	Descriptions
#  --------------------------------------------------------------------------
#   1.0.0	20090601	Kane Lai	First release
#
################################################################################


version="1.0.0"

if [ $# -lt 1 ]; then
	echo "expschema v$version - A tool to export schema from Oracle Database"
	echo "Exported SQL scripts will be in the current directory"
	echo "Usage:\t$0 [db_conn_str [options]]"
	echo "    \"db_conn_str\": Oracle Database connection string to be passed to sqlplus, e.g. admin/mypassword@ora10g"
	echo "    \"options\": Indicates which of (t)ables, (v)iews, (s)ynonyms, t(y)pes, se(q)uences, (p)ackages, t(r)iggers, (f)unctions and pr(o)cedures should be exported, e.g. tvsyprfo would export everything except sequences"
	exit 1
fi

if [ $# -gt 1 ]; then
	is_custom=1
else
	is_custom=0
fi

db_conn_str=$1
is_conn_str_ok=`echo $db_conn_str | grep -ic /`
if [ $is_conn_str_ok -ne 1 ]; then
	echo "Oracle Database connection string must be of the format \"username/password[@connect_identifier]\""
	exit 1
fi

if [ $is_custom -eq 0 ] || [ `echo "$2" | grep -c t` -gt 0 ]; then
	echo "--------------------------------------------------------"
	echo "["`date +"%Y-%m-%d %T"`"] Executing exptaball..."
	echo "--------------------------------------------------------"
	`dirname $0`/exptaball $db_conn_str
fi
if [ $is_custom -eq 0 ] || [ `echo "$2" | grep -c v` -gt 0 ]; then
	echo "--------------------------------------------------------"
	echo "["`date +"%Y-%m-%d %T"`"] Executing expviewall..."
	echo "--------------------------------------------------------"
	`dirname $0`/expviewall $db_conn_str
fi
if [ $is_custom -eq 0 ] || [ `echo "$2" | grep -c s` -gt 0 ]; then
	echo "--------------------------------------------------------"
	echo "["`date +"%Y-%m-%d %T"`"] Executing expsynall..."
	echo "--------------------------------------------------------"
	`dirname $0`/expsynall $db_conn_str
fi
if [ $is_custom -eq 0 ] || [ `echo "$2" | grep -c y` -gt 0 ]; then
	echo "--------------------------------------------------------"
	echo "["`date +"%Y-%m-%d %T"`"] Executing exptypeall..."
	echo "--------------------------------------------------------"
	`dirname $0`/exptypeall $db_conn_str
fi
if [ $is_custom -eq 0 ] || [ `echo "$2" | grep -c q` -gt 0 ]; then
	echo "--------------------------------------------------------"
	echo "["`date +"%Y-%m-%d %T"`"] Executing expseqall..."
	echo "--------------------------------------------------------"
	`dirname $0`/expseqall $db_conn_str
fi
if [ $is_custom -eq 0 ] || [ `echo "$2" | grep -c p` -gt 0 ]; then
	echo "--------------------------------------------------------"
	echo "["`date +"%Y-%m-%d %T"`"] Executing exppkgall..."
	echo "--------------------------------------------------------"
	`dirname $0`/exppkgall $db_conn_str
fi
if [ $is_custom -eq 0 ] || [ `echo "$2" | grep -c r` -gt 0 ]; then
	echo "--------------------------------------------------------"
	echo "["`date +"%Y-%m-%d %T"`"] Executing exptrgall..."
	echo "--------------------------------------------------------"
	`dirname $0`/exptrgall $db_conn_str
fi
if [ $is_custom -eq 0 ] || [ `echo "$2" | grep -c f` -gt 0 ]; then
	echo "--------------------------------------------------------"
	echo "["`date +"%Y-%m-%d %T"`"] Executing expfuncall..."
	echo "--------------------------------------------------------"
	`dirname $0`/expfuncall $db_conn_str
fi
if [ $is_custom -eq 0 ] || [ `echo "$2" | grep -c o` -gt 0 ]; then
	echo "--------------------------------------------------------"
	echo "["`date +"%Y-%m-%d %T"`"] Executing expprocall..."
	echo "--------------------------------------------------------"
	`dirname $0`/expprocall $db_conn_str
fi
echo "--------------------------------------------------------"
echo "["`date +"%Y-%m-%d %T"`"] Done"
echo "--------------------------------------------------------"

